import {createClient} from "@supabase/supabase-js";
import {LocalNotifications} from "@capacitor/local-notifications";
import {SpeechRecognition} from "@capacitor-community/speech-recognition";
import "./style.css";
import {noriIntent,mentorDirective,executeLocalIntent,systemHealth,routeAction,connectedSystemContract} from "./nori-system.js";
const SUPABASE_URL="https://qrlvkxewyoceykaquapv.supabase.co",KEY="sb_publishable_3QSgkXgNWRa82Z2ID6n7Ag_QdvmH92_",BRAIN=SUPABASE_URL+"/functions/v1/nori-brain";
const db=createClient(SUPABASE_URL,KEY),STORE="nori.rebuild.v1";
const defaults={messages:[],subjects:[],sessions:[],tasks:[],errors:[],assessments:[],plans:[],notes:[],points:0,phase:1,recovery:null,active:null,settings:{voice:"en-US",deep:true}};
const NORI_CONTRACT=connectedSystemContract();
let S=load(),page="home",listening=false,heard="",timer=0,level=0,stream=null,audio=null,analyser=null,raf=0;
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(STORE)||"{}")}}catch{return {...defaults}}}
function save(){localStorage.setItem(STORE,JSON.stringify(S))}
function uid(){return crypto.randomUUID()} function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function card(t,b){return '<section class="card"><div class="cardhead"><b>'+t+'</b></div>'+b+'</section>'}
function shell(body){let ns=["home","study","tracker","recovery","profile"];return '<div class="app"><header><div class="brand"><div class="avatar">N</div><div><b>Nori</b><span>connected intelligence</span></div></div><button class="status">● online</button></header><main>'+body+'</main><nav>'+ns.map(n=>'<button class="'+(page===n?"active":"")+'" data-nav="'+n+'"><span>'+({home:"⌂",study:"◫",tracker:"◈",recovery:"↺",profile:"○"})[n]+'</span>'+n[0].toUpperCase()+n.slice(1)+'</button>').join("")+'</nav></div>'}
function home(){let health=systemHealth(S);let next=S.tasks.find(x=>!x.done)||S.plans[S.plans.length-1];return shell('<div class="hero"><div><small>TODAY COMMAND</small><h1>Nori is ready.</h1><p>Conversation is a capability inside one connected system.</p></div><button class="primary" data-a="chat">Meet Nori</button></div>'+card("Nori system",'<div class="grid4"><div><small>Capabilities</small><strong>'+health.enabled+'</strong></div><div><small>Mode</small><strong>Adaptive</strong></div><div><small>Provider</small><strong>Connected</strong></div><div><small>Chat</small><strong>Feature</strong></div></div>')+card("Live state",'<div class="grid4"><div><small>Phase</small><strong>'+S.phase+'</strong></div><div><small>Merit</small><strong>'+S.points+'</strong></div><div><small>Sessions</small><strong>'+S.sessions.length+'</strong></div><div><small>Tasks</small><strong>'+S.tasks.filter(x=>!x.done).length+'</strong></div></div>')+card("Next move",next?'<div class="row"><span><b>'+esc(next.title||next.topic)+'</b><small>'+esc(next.subject||"planned")+'</small></span><button data-a="open-next">Open</button></div>':"<p>Ask Nori to build the next study block from your real state.</p>")+card("Tools",'<div class="chips"><button data-a="calc">Calculator</button><button data-a="alarm">Alarm</button><button data-a="plan">Plan block</button><button data-a="note">Note</button></div>')}
function study(){let a=S.active;return shell('<div class="pagehead"><div><small>ACADEMIC ENGINE</small><h2>Study</h2><p>Plan → work → evidence → correction → verification.</p></div><button class="primary" data-a="start">'+(a?"Continue":"Start session")+'</button></div>'+(a?card("Current study block",'<b>'+esc(a.subject)+" · "+esc(a.topic)+'</b><p>'+esc(a.plan)+'</p><button data-a="finish">Finish and record</button>'):"")+card("Plans",S.plans.slice(-8).reverse().map(p=>'<div class="listrow"><span><b>'+esc(p.title)+'</b><small>'+esc(p.subject||"")+'</small></span><button data-a="use" data-id="'+p.id+'">Use</button></div>').join("")||"<p>No plans yet.</p>")+card("Prepare",'<div class="chips"><button data-a="quick" data-q="Prepare notes for my current weak area.">Notes</button><button data-a="quick" data-q="Generate practice for my weakest topic.">Practice</button><button data-a="quick" data-q="Analyze my recurring errors.">Errors</button><button data-a="quick" data-q="Prepare my next exam plan.">Exam</button></div>')}
function tracker(){return shell('<div class="pagehead"><div><small>EVIDENCE</small><h2>Tracker</h2><p>Results, errors, plans and progress stay connected.</p></div><button data-a="score">Record</button></div>'+card("Snapshot",'<div class="grid4"><div><small>Results</small><strong>'+S.assessments.length+'</strong></div><div><small>Errors</small><strong>'+S.errors.length+'</strong></div><div><small>Plans</small><strong>'+S.plans.length+'</strong></div><div><small>Notes</small><strong>'+S.notes.length+'</strong></div></div>')+card("Recent results",S.assessments.slice(-6).reverse().map(x=>'<div class="listrow"><span><b>'+esc(x.subject)+'</b><small>'+esc(x.type)+' · '+x.score+'%</small></span><span>'+ (x.score>=80?"✓":"repair")+'</span></div>').join("")||"<p>No results recorded.</p>")+card("Errors",S.errors.slice(-6).reverse().map(x=>'<div class="listrow"><span><b>'+esc(x.subject)+' · '+esc(x.topic)+'</b><small>'+esc(x.cause)+'</small></span><button data-a="quick" data-q="Help me repair this '+esc(x.subject)+' error: '+esc(x.topic)+' caused by '+esc(x.cause)+'.">Repair</button></div>').join("")||"<p>No errors recorded.</p>")}
function recovery(){return shell('<div class="pagehead"><div><small>RESTORATION</small><h2>Recovery</h2><p>Cause → repair → verify → restore. No unsafe penalties.</p></div></div>'+(S.recovery?card("Active recovery",'<b>'+esc(S.recovery.reason)+'</b><p>'+S.recovery.progress+'% verified progress</p><div class="bar"><i style="width:'+S.recovery.progress+'%"></i></div><button data-a="verify">Verify</button>'):card("Stable",'<p>No recovery gate is active. Human circumstances are considered before protected decisions.</p><button data-a="recover">Start recovery review</button>'))+card("Human Override",'<p>Sleep, health, safety, family responsibilities, emergencies and genuine unavoidable constraints remain protected context.</p>'))}
function profile(){return shell('<div class="pagehead"><div><small>SYSTEM</small><h2>Profile</h2><p>Account, model routing, voice and local data.</p></div></div>'+card("Account",'<div id="acct">Checking…</div><div class="chips"><button data-a="login">Sign in</button><button data-a="logout">Sign out</button></div>')+card("AI routing",'<div class="listrow"><span><b>Automatic model change</b><small>Fast for simple work, deeper route for complex/academic work.</small></span><b>ON</b></div><div class="listrow"><span><b>Voice patience</b><small>Extended listening, amplitude monitoring and restart supervision.</small></span><b>ON</b></div>')+card("Data",'<div class="chips"><button data-a="export">Export backup</button><button data-a="reset">Reset local data</button></div>'))}
function chat(){return shell('<div class="chat"><div class="chathead"><div><small>MEET NORI</small><h2>Conversation</h2><p>Chat is a feature. Home, Study, Tracker, Recovery and Profile remain one system.</p></div><span class="mode">'+(listening?"LISTENING":"READY")+'</span></div><div class="messages" id="msgs">'+S.messages.map(m=>'<div class="msg '+m.role+'"><div>'+esc(m.text)+'</div></div>').join("")+'</div><div class="composer"><button class="mic '+(listening?"on":"")+'" id="mic">'+(listening?"■":"●")+'</button><textarea id="input" placeholder="Ask Nori anything…"></textarea><button class="send" id="send">Send</button></div><div class="chips"><button data-a="quick" data-q="Give me my current status from recorded evidence only.">Status</button><button data-a="quick" data-q="What should I study now?">Study now</button><button data-a="quick" data-q="Show my weakest areas and the evidence.">Weak areas</button><button data-a="quick" data-q="Plan my next study block.">Plan</button></div></div>')}
function render(){let root=document.getElementById("app");root.innerHTML=page==="chat"?chat():({home,study,tracker,recovery,profile}[page]||home);document.querySelectorAll("[data-nav]").forEach(x=>x.onclick=()=>{page=x.dataset.nav;render()});document.querySelectorAll("[data-a]").forEach(x=>x.onclick=()=>act(x.dataset.a,x.dataset.id,x.dataset.q));let send=document.getElementById("send");if(send)send.onclick=sendMsg;let mic=document.getElementById("mic");if(mic)mic.onclick=voice;let msgs=document.getElementById("msgs");if(msgs)msgs.scrollTop=msgs.scrollHeight;let acct=document.getElementById("acct");if(acct)db.auth.getUser().then(r=>acct.innerHTML=r.data.user?"Signed in as <b>"+esc(r.data.user.email)+"</b>":"Not signed in")}
async function act(a,id,q){if(a==="chat"){page="chat";render();return}if(a==="calc"){let e=prompt("Expression");if(!e)return;try{let safe=e.replace(/[^0-9+\\-*/().%\\s]/g,"");page="chat";add("nori","Calculator result: "+Function("return("+safe+")")())}catch{alert("Invalid expression.")}return}if(a==="alarm"){let m=Number(prompt("Minutes from now","30"));if(!m)return;await LocalNotifications.requestPermissions();await LocalNotifications.schedule({notifications:[{id:Date.now()%2147483647,title:"Nori reminder",body:"Your planned block is ready.",schedule:{at:new Date(Date.now()+m*60000)}}]});alert("Reminder scheduled.");return}if(a==="plan"){let s=prompt("Subject","Biology"),t=prompt("Topic","Weak topic");if(!s||!t)return;S.plans.push({id:uid(),title:"Focused "+t,subject:s,topic:t,plan:"Recall → learn → practice → correct → verify"});save();page="study";render();return}if(a==="note"){let n=prompt("Note");if(n){S.notes.push({id:uid(),text:n,time:Date.now()});save();alert("Saved locally.")}return}if(a==="start"){let s=prompt("Subject","Biology"),t=prompt("Topic","Current topic");if(!s||!t)return;S.active={id:uid(),subject:s,topic:t,started:Date.now(),plan:"Understand → practice → correct → verify"};save();render();return}if(a==="finish"){S.sessions.push({...S.active,ended:Date.now()});S.active=null;save();render();return}if(a==="score"){let s=prompt("Subject","Biology"),n=Number(prompt("Score %","80"));if(!s||!Number.isFinite(n))return;S.assessments.push({id:uid(),subject:s,score:Math.max(0,Math.min(100,n)),type:prompt("Type","Weekly"),date:Date.now()});save();page="tracker";render();return}if(a==="recover"){S.recovery={id:uid(),reason:"Recovery review",progress:0};save();render();return}if(a==="verify"){S.recovery=null;save();render();return}if(a==="export"){let u=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:"application/json"})),el=document.createElement("a");el.href=u;el.download="nori-backup.json";el.click();URL.revokeObjectURL(u);return}if(a==="reset"){if(confirm("Reset local Nori data?")){localStorage.removeItem(STORE);location.reload()}return}if(a==="login"){let e=prompt("Email"),p=prompt("Password");if(e&&p){let r=await db.auth.signInWithPassword({email:e,password:p});alert(r.error?r.error.message:"Signed in.");render()}return}if(a==="logout"){await db.auth.signOut();render();return}if(a==="use"){let p=S.plans.find(x=>x.id===id);if(p){S.active={...p,started:Date.now()};save();page="study";render()}return}if(a==="open-next"){page="study";render();return}if(a==="quick"){page="chat";render();let i=document.getElementById("input");if(i){i.value=q;sendMsg()}return}}
function add(role,text){S.messages.push({id:uid(),role,text,time:Date.now()});S.messages=S.messages.slice(-100);save();render()}
function stateForBrain(){return {phase:S.phase,points:S.points,activeSession:S.active,recovery:S.recovery,tasks:S.tasks.filter(x=>!x.done).slice(0,15),plans:S.plans.slice(-10),sessions:S.sessions.slice(-10),assessments:S.assessments.slice(-15),errors:S.errors.slice(-15),notes:S.notes.slice(-10)}}
async function sendMsg(){let i=document.getElementById("input"),text=i?.value.trim();if(!text)return;i.value="";add("user",text);add("nori","Thinking…");let idx=S.messages.length-1;try{let r=await db.auth.getSession();if(!r.data.session)throw new Error("SIGN_IN_REQUIRED");let res=await fetch(BRAIN,{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+r.data.session.access_token},body:JSON.stringify({message:text,actionRoute:routeAction(text,S),systemContract:NORI_CONTRACT,history:S.messages.slice(-15),stateSummary:stateForBrain(),brainContext:{subjects:S.subjects,intent:noriIntent(text,S),mentor:mentorDirective(noriIntent(text,S),S),systemHealth:systemHealth(S)},nextMove:{active:S.active,plans:S.plans.slice(-5),local:executeLocalIntent(noriIntent(text,S),text,stateForBrain())}})}),data=await res.json();if(!res.ok||!data.reply)throw new Error(data.error||"BRAIN_UNAVAILABLE");S.messages.splice(idx,1);save();add("nori",data.reply)}catch(e){S.messages.splice(idx,1);save();add("nori","I kept your request locally. The protected AI connection is unavailable right now: "+e.message)}}
async function voice(){if(listening){stopVoice();return}try{let p=await SpeechRecognition.requestPermissions();if(p.speechRecognition!=="granted")throw Error("Speech permission required");listening=true;heard="";render();monitor();listen()}catch(e){alert(e.message)}}
async function listen(){if(!listening)return;try{await SpeechRecognition.start({language:S.settings.voice,maxResults:5,partialResults:true,popup:false});clearTimeout(timer);timer=setTimeout(()=>{if(!listening)return;if(heard.trim()){let t=heard;stopVoice();page="chat";render();document.getElementById("input").value=t;sendMsg()}else listen()},30000)}catch{if(listening)setTimeout(listen,1000)}}
SpeechRecognition.addListener("partialResults",r=>{let x=(r.matches||[]).join(" ").trim();if(x){heard=x;let i=document.getElementById("input");if(i)i.value=x}});
SpeechRecognition.addListener("listeningState",r=>{if(listening&&r.status==="stopped")setTimeout(listen,700)});
async function monitor(){try{stream=await navigator.mediaDevices.getUserMedia({audio:true});audio=new AudioContext();analyser=audio.createAnalyser();analyser.fftSize=512;audio.createMediaStreamSource(stream).connect(analyser);let data=new Uint8Array(analyser.fftSize);function tick(){if(!listening)return;analyser.getByteTimeDomainData(data);let sum=0;for(let v of data){let x=(v-128)/128;sum+=x*x}level=Math.min(1,Math.sqrt(sum/data.length)*5);document.documentElement.style.setProperty("--voice-level",level);raf=requestAnimationFrame(tick)}tick()}catch{}}
function stopVoice(){listening=false;clearTimeout(timer);cancelAnimationFrame(raf);stream?.getTracks().forEach(x=>x.stop());stream=null;audio?.close();audio=null;analyser=null;document.documentElement.style.setProperty("--voice-level",0);SpeechRecognition.stop().catch(()=>{});render()}
db.auth.onAuthStateChange(()=>render());render();